### ISSUE TITLE
Directly parsing the cookie content as JSON can throw an error if the content is malformed

### ISSUE THREAD

**Issue by guilhermehn** [omichelsen/express-ab#15]
I'm heaving trouble with a malformed cookie. The actual content of the cookie is this:

`%7B%22ps-website-switching%22%3A%22ps-website%22`

Which translates to: 

`{"ps-website-switching":"ps-website"`

It's missing the closing bracket, which gives this error stack:

```
defaultSyntaxError: Unexpected token / in JSON at position 0 SyntaxError: Unexpected token / in JSON at position 0
   at Object.parse (native)
   at getCookie (/usr/src/app/node_modules/express-ab/lib/express-ab.js:23:25)
   at /usr/src/app/node_modules/express-ab/lib/express-ab.js:52:26
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
   at /usr/src/app/node_modules/express/lib/router/index.js:284:7
   at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
   at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
   at cookieParser (/usr/src/app/node_modules/cookie-parser/index.js:70:5)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
```

I think this can be solved quite easily just by wrapping the [`JSON.parse`](https://github.com/omichelsen/express-ab/blob/4ac6f7aa44f4f8dffadca3b0470a24cd2e9571d1/lib/express-ab.js#L23) call in a `try catch` block.

**Comment by omichelsen** [comment]
Yeah the lib shouldn't fail if given a bad cookie. Will add that.

**Comment by guilhermehn** [comment]
Thanks!
